// react/button/button.tsx
import React from 'react';
import './button.css';

export type ButtonProps = {
  type?: 'primary' | 'secondary' | 'destructive' | 'remotecontrol';
  interactionState?: 'hover' | 'focus' | 'selected';
  disabled?: boolean;
  icon?: React.ReactNode;
  label?: string;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
  className?: string;
  style?: React.CSSProperties;
};

export const Button: React.FC<ButtonProps> = ({
  type = 'primary',
  interactionState,
  disabled = false,
  icon,
  label,
  onClick,
  className = '',
  style = {},
  ...rest
}) => {
  let btnClass = `btn btn-${type}`;
  if (interactionState) btnClass += ` btn-${interactionState}`;
  if (disabled) btnClass += ' btn-disabled';
  if (className) btnClass += ` ${className}`;

  return (
    <button
      type="button"
      className={btnClass}
      disabled={disabled}
      onClick={onClick}
      style={style}
      {...rest}
    >
      {icon && <span className="btn-icon">{icon}</span>}
      {label}
    </button>
  );
};

// angular/button/button.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-button',
  template: `
    <button
      type="button"
      class="btn btn-{{type}}"
      [class.btn-hover]="interactionState === 'hover'"
      [class.btn-focus]="interactionState === 'focus'"
      [class.btn-selected]="interactionState === 'selected'"
      [class.btn-disabled]="disabled"
      [disabled]="disabled"
      (click)="onClick.emit($event)"
    >
      <span *ngIf="icon" class="btn-icon">{{ icon }}</span>
      {{ label }}
    </button>
  `,
  styleUrls: ['./button.css']
})
export class ButtonComponent {
  @Input() type: 'primary' | 'secondary' | 'destructive' | 'remotecontrol' = 'primary';
  @Input() interactionState?: 'hover' | 'focus' | 'selected';
  @Input() disabled = false;
  @Input() icon?: string;
  @Input() label?: string;
  @Output() onClick = new EventEmitter<Event>();
}
