// react/button-fab/ButtonFab.component.tsx
// Floating Action Button (FAB) – React-Implementierung nach Figma
import React from "react";
import "./ButtonFab.component.css";

export interface ButtonFabProps {
  iconSrc: string;
  label?: string;
  size?: "md" | "lg";
  interactionState?: "default" | "hover" | "focus" | "focus-visible" | "pressed" | "disabled";
  semanticState?: "default" | "destructive" | "disabled" | "remotecontrol";
}

export const ButtonFab: React.FC<ButtonFabProps> = ({
  iconSrc,
  label,
  size = "lg",
  interactionState = "default",
  semanticState = "default",
}) => {
  const classNames = [
    "fab-root",
    `fab-${size}`,
    `fab-${interactionState}`,
    `fab-sem-${semanticState}`,
    semanticState === "disabled" ? "fab-disabled" : "",
    interactionState === "hover" ? "fab-hover" : "",
    interactionState === "focus" ? "fab-focus" : "",
    interactionState === "focus-visible" ? "fab-focus-visible" : "",
    interactionState === "pressed" ? "fab-pressed" : "",
  ].join(" ");

  return (
    <button
      className={classNames}
      tabIndex={interactionState !== "disabled" && semanticState !== "disabled" ? 0 : -1}
      disabled={interactionState === "disabled" || semanticState === "disabled"}
    >
      <span className="fab-icon">
        <img src={iconSrc} alt="FAB Icon" />
      </span>
      {label && <span className="fab-label">{label}</span>}
    </button>
  );
};

export default ButtonFab;

// angular/button-fab/ButtonFab.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-button-fab',
  templateUrl: './ButtonFab.component.html',
  styleUrls: ['./ButtonFab.component.css']
})
export class ButtonFabComponent {
  @Input() iconSrc!: string;
  @Input() label?: string;
  @Input() size: 'md' | 'lg' = 'lg';
  @Input() interactionState: 'default' | 'hover' | 'focus' | 'focus-visible' | 'pressed' | 'disabled' = 'default';
  @Input() semanticState: 'default' | 'destructive' | 'disabled' | 'remotecontrol' = 'default';
}

<button
  class="fab-root fab-{{size}} fab-{{interactionState}} fab-sem-{{semanticState}}"
  [attr.tabindex]="interactionState !== 'disabled' && semanticState !== 'disabled' ? 0 : -1"
  [disabled]="interactionState === 'disabled' || semanticState === 'disabled'"
>
  <span class="fab-icon">
    <img [src]="iconSrc" alt="FAB Icon" />
  </span>
  <span *ngIf="label" class="fab-label">{{label}}</span>
</button>
